/**
 * The mistakes loop — the part that has to be right for the feature to mean anything.
 *
 * The whole idea is that the list SHRINKS: get a question right and it disappears.
 * That depends entirely on the id being derived from the question text, so a
 * question saved on Monday can be matched and deleted on Friday, on another device,
 * from a completely separate generation that happened to produce the same question.
 *
 * Run: npx vitest run tests/mistakes.test.ts
 */
import { describe, expect, it } from 'vitest';
import { questionId } from '../src/lib/questionId';

describe('question identity', () => {

  it('is stable for the same question', () => {
    // If this were random, retiring a mistake could never find the row to delete.
    const a = questionId('What is the powerhouse of the cell?');
    const b = questionId('What is the powerhouse of the cell?');
    expect(a).toBe(b);
  });

  it('ignores casing and stray whitespace', () => {
    // The same question re-generated by an AI rarely comes back byte-identical.
    const base = questionId('What is 7 + 5?');
    expect(questionId('  what is 7 + 5?  ')).toBe(base);
    expect(questionId('What  is   7 + 5?')).toBe(base);
    expect(questionId('WHAT IS 7 + 5?')).toBe(base);
  });

  it('differs for different questions', () => {
    expect(questionId('What is 7 + 5?')).not.toBe(questionId('What is 7 + 6?'));
  });

  it('is a short, storage-safe key', () => {
    const id = questionId('a'.repeat(5000));
    expect(id).toMatch(/^q[0-9a-z]+$/);
    expect(id.length).toBeLessThan(12);
  });

  it('survives punctuation and unicode without throwing', () => {
    for (const q of ['', '   ', 'Qué es la célula?', '∫x dx = ?', '"quoted" — dash']) {
      expect(() => questionId(q)).not.toThrow();
      expect(questionId(q)).toMatch(/^q[0-9a-z]+$/);
    }
  });

  it('does not collide across a realistic question set', () => {
    // A weak hash here would silently retire the WRONG question — the user would
    // fix one thing and watch a different one vanish.
    const questions: string[] = [];
    for (let i = 0; i < 2000; i++) {
      questions.push(`What is ${i} multiplied by ${i + 3}?`);
      questions.push(`Define term number ${i} in biology`);
    }
    const ids = new Set(questions.map(questionId));
    expect(ids.size).toBe(questions.length);
  });
});
